CREATE TABLE CLIENTE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CPF VARCHAR(11),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(11)
);

CREATE TABLE PRODUTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255)
);

CREATE TABLE PEDIDO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2),
    STATUS VARCHAR(20)
);

CREATE TABLE PEDIDO_ITEM(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO(ID),
    QUANTIDADE INTEGER
);
